import {
  DispatchQueue,
  RideNode,
  calculateFare,
  euclideanDistance,
  type DemandLevel,
  type Driver,
  type DriverStatus,
  type Point,
} from "./dsa";

export interface LogEntry {
  id: string;
  time: string;
  message: string;
  operation: "ENQUEUE" | "DEQUEUE" | "CANCEL" | "LOOKUP" | "PRICE" | "SYSTEM";
  complexity: string;
}

export interface Pricing {
  baseFare: number;
  ratePerUnit: number;
}

export interface Stats {
  matched: number;
  cancelled: number;
}

export interface CancelStep {
  title: string;
  detail: string;
}

const STORAGE_KEY = "rideshare-dispatch-state-v1";

function nowTime() {
  return new Date().toLocaleTimeString("en-GB", { hour12: false });
}

let idCounter = 0;
function uid() {
  idCounter += 1;
  return `${Date.now().toString(36)}-${idCounter}`;
}

class SimulationStore {
  queue = new DispatchQueue();
  driverMap: Map<string, Driver> = new Map();
  logs: LogEntry[] = [];
  pricing: Pricing = { baseFare: 50, ratePerUnit: 15 };
  stats: Stats = { matched: 0, cancelled: 0 };
  rideCounter = 100;
  driverCounter = 0;
  /** last cancellation walkthrough (generated by the real algorithm) */
  lastCancelSteps: CancelStep[] = [];
  lastCancelledId: string | null = null;
  hydrated = false;

  version = 0;
  private listeners = new Set<() => void>();

  subscribe = (cb: () => void) => {
    this.listeners.add(cb);
    return () => this.listeners.delete(cb);
  };

  getVersion = () => this.version;

  private emit(persist = true) {
    this.version++;
    if (persist) this.persist();
    this.listeners.forEach((l) => l());
  }

  log(message: string, operation: LogEntry["operation"], complexity: string) {
    this.logs = [
      { id: uid(), time: nowTime(), message, operation, complexity },
      ...this.logs,
    ].slice(0, 200);
  }

  // ---------------- rides ----------------

  nextRideId(): string {
    return `RIDE-${this.rideCounter + 1}`;
  }

  addRide(input: {
    riderName: string;
    pickup: Point;
    drop: Point;
    demandLevel: DemandLevel;
  }): RideNode {
    const name = input.riderName.trim();
    if (!name) throw new Error("Rider name cannot be empty.");
    const coords = [input.pickup.x, input.pickup.y, input.drop.x, input.drop.y];
    if (coords.some((c) => !Number.isFinite(c))) {
      throw new Error("Coordinates must be valid numbers.");
    }
    if (this.pricing.baseFare < 0 || this.pricing.ratePerUnit < 0) {
      throw new Error("Pricing values cannot be negative.");
    }
    const distance = euclideanDistance(input.pickup, input.drop);
    const fare = calculateFare(
      distance,
      input.demandLevel,
      this.pricing.baseFare,
      this.pricing.ratePerUnit,
    );
    this.rideCounter += 1;
    const node = new RideNode({
      rideId: `RIDE-${this.rideCounter}`,
      riderName: name,
      pickup: input.pickup,
      drop: input.drop,
      distance: Math.round(distance * 100) / 100,
      fare,
      demandLevel: input.demandLevel,
    });
    this.queue.enqueue(node);
    this.log(`${node.rideId} added to queue (tail insert)`, "ENQUEUE", "O(1)");
    this.emit();
    return node;
  }

  cancelRide(rideId: string): CancelStep[] {
    const node = this.queue.rideMap.get(rideId);
    if (!node) {
      throw new Error(`Ride "${rideId}" does not exist in the dispatch queue.`);
    }
    const prevId = node.prev?.rideId ?? "HEAD";
    const nextId = node.next?.rideId ?? "TAIL";

    const steps: CancelStep[] = [
      { title: "STEP 1 — Request", detail: `User requests cancellation of ${rideId}` },
      { title: "STEP 2 — Hash Map lookup", detail: `rideMap.get("${rideId}")  →  O(1)` },
      { title: "STEP 3 — Node found", detail: `Direct reference to node ${rideId} obtained` },
      {
        title: "STEP 4 — Read pointers",
        detail: `${rideId}.prev = ${prevId}   |   ${rideId}.next = ${nextId}`,
      },
      {
        title: "STEP 5 — Reconnect",
        detail:
          `${prevId === "HEAD" ? `head = ${nextId}` : `${prevId}.next = ${nextId}`}  |  ` +
          `${nextId === "TAIL" ? `tail = ${prevId}` : `${nextId}.prev = ${prevId}`}`,
      },
      { title: "STEP 6 — Delete entry", detail: `rideMap.delete("${rideId}")` },
    ];

    this.queue.cancel(rideId);
    this.stats.cancelled += 1;
    this.lastCancelSteps = steps;
    this.lastCancelledId = rideId;
    this.log(`${rideId} cancelled`, "CANCEL", "O(1)");
    this.emit();
    return steps;
  }

  /** Match head of queue with the first Available driver in the driver hash map. */
  matchNextRide(): { ride: RideNode; driver: Driver } {
    if (this.queue.isEmpty()) {
      throw new Error("No ride requests in queue.");
    }
    let available: Driver | undefined;
    for (const driver of this.driverMap.values()) {
      if (driver.status === "Available") {
        available = driver;
        break;
      }
    }
    if (!available) {
      throw new Error("No drivers currently available.");
    }
    const ride = this.queue.dequeue()!;
    ride.status = "Matched";
    ride.assignedDriverId = available.driverId;
    available.status = "Busy";
    available.currentRide = ride.rideId;
    this.driverMap.set(available.driverId, available);
    this.stats.matched += 1;
    this.log(
      `${ride.rideId} matched with ${available.driverId}`,
      "DEQUEUE",
      "O(1)",
    );
    this.emit();
    return { ride, driver: available };
  }

  // ---------------- drivers ----------------

  addDriver(name: string, x: number, y: number): Driver {
    this.driverCounter += 1;
    const id = `DRIVER-${String(this.driverCounter).padStart(2, "0")}`;
    const driver: Driver = {
      driverId: id,
      name,
      locationX: x,
      locationY: y,
      status: "Available",
      currentRide: null,
    };
    this.driverMap.set(id, driver);
    return driver;
  }

  setDriverStatus(driverId: string, status: DriverStatus) {
    const driver = this.driverMap.get(driverId); // O(1) hash map lookup
    if (!driver) throw new Error(`Driver "${driverId}" not found.`);
    driver.status = status;
    if (status === "Available") driver.currentRide = null;
    this.driverMap.set(driverId, driver);
    this.log(`${driverId} status set to ${status}`, "LOOKUP", "O(1)");
    this.emit();
  }

  resetDriver(driverId: string) {
    const driver = this.driverMap.get(driverId);
    if (!driver) throw new Error(`Driver "${driverId}" not found.`);
    driver.status = "Available";
    driver.currentRide = null;
    this.driverMap.set(driverId, driver);
    this.log(`${driverId} reset to Available`, "LOOKUP", "O(1)");
    this.emit();
  }

  setPricing(pricing: Partial<Pricing>) {
    const next = { ...this.pricing, ...pricing };
    if (next.baseFare < 0 || next.ratePerUnit < 0) {
      throw new Error("Pricing values cannot be negative.");
    }
    this.pricing = next;
    this.emit();
  }

  // ---------------- bulk actions ----------------

  loadSampleData() {
    const drivers: Array<[string, number, number]> = [
      ["Ravi Kumar", 5, 8],
      ["Meena Iyer", 12, 3],
      ["Arun Das", 2, 14],
      ["Sneha Rao", 18, 11],
      ["Karthik S", 9, 6],
      ["Farah Khan", 15, 17],
    ];
    drivers.forEach(([n, x, y]) => this.addDriver(n, x, y));

    const rides: Array<[string, Point, Point, DemandLevel]> = [
      ["Rahul", { x: 2, y: 3 }, { x: 10, y: 8 }, "Normal"],
      ["Priya", { x: 4, y: 9 }, { x: 14, y: 2 }, "High"],
      ["Arjun", { x: 1, y: 1 }, { x: 6, y: 5 }, "Low"],
      ["Neha", { x: 11, y: 12 }, { x: 3, y: 4 }, "Very High"],
      ["Vikram", { x: 7, y: 7 }, { x: 16, y: 13 }, "Normal"],
    ];
    rides.forEach(([name, pickup, drop, demand]) => {
      const distance = euclideanDistance(pickup, drop);
      this.rideCounter += 1;
      this.queue.enqueue(
        new RideNode({
          rideId: `RIDE-${this.rideCounter}`,
          riderName: name,
          pickup,
          drop,
          distance: Math.round(distance * 100) / 100,
          fare: calculateFare(
            distance,
            demand,
            this.pricing.baseFare,
            this.pricing.ratePerUnit,
          ),
          demandLevel: demand,
        }),
      );
    });
    this.log(
      `Sample data loaded: ${drivers.length} drivers, ${rides.length} rides`,
      "SYSTEM",
      "O(D + R)",
    );
    this.emit();
  }

  reset() {
    this.queue = new DispatchQueue();
    this.driverMap = new Map();
    this.logs = [];
    this.stats = { matched: 0, cancelled: 0 };
    this.rideCounter = 100;
    this.driverCounter = 0;
    this.lastCancelSteps = [];
    this.lastCancelledId = null;
    this.pricing = { baseFare: 50, ratePerUnit: 15 };
    this.log("Simulation reset — all structures cleared", "SYSTEM", "O(1)");
    if (typeof window !== "undefined") localStorage.removeItem(STORAGE_KEY);
    this.emit(false);
  }

  // ---------------- persistence ----------------

  private persist() {
    if (typeof window === "undefined" || !this.hydrated) return;
    try {
      const data = {
        rides: this.queue.getAllRequests().map((n) => ({
          rideId: n.rideId,
          riderName: n.riderName,
          pickup: n.pickup,
          drop: n.drop,
          distance: n.distance,
          fare: n.fare,
          demandLevel: n.demandLevel,
          status: n.status,
          createdAt: n.createdAt,
        })),
        drivers: [...this.driverMap.values()],
        logs: this.logs,
        stats: this.stats,
        pricing: this.pricing,
        rideCounter: this.rideCounter,
        driverCounter: this.driverCounter,
      };
      localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
    } catch {
      /* storage unavailable — simulation still works in memory */
    }
  }

  hydrate() {
    if (this.hydrated || typeof window === "undefined") return;
    this.hydrated = true;
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (!raw) {
        this.emit(false);
        return;
      }
      const data = JSON.parse(raw);
      this.queue = new DispatchQueue();
      for (const r of data.rides ?? []) {
        this.queue.enqueue(new RideNode(r));
      }
      this.driverMap = new Map(
        (data.drivers ?? []).map((d: Driver) => [d.driverId, d]),
      );
      this.logs = data.logs ?? [];
      this.stats = data.stats ?? { matched: 0, cancelled: 0 };
      this.pricing = data.pricing ?? { baseFare: 50, ratePerUnit: 15 };
      this.rideCounter = data.rideCounter ?? 100;
      this.driverCounter = data.driverCounter ?? 0;
    } catch {
      /* corrupted state — start fresh */
    }
    this.emit(false);
  }

  // ---------------- derived ----------------

  get drivers(): Driver[] {
    return [...this.driverMap.values()];
  }

  get rides(): RideNode[] {
    return this.queue.getAllRequests();
  }

  get availableCount(): number {
    return this.drivers.filter((d) => d.status === "Available").length;
  }

  get busyCount(): number {
    return this.drivers.filter((d) => d.status === "Busy").length;
  }

  get averageFare(): number {
    const rides = this.rides;
    if (!rides.length) return 0;
    return (
      Math.round((rides.reduce((s, r) => s + r.fare, 0) / rides.length) * 100) / 100
    );
  }
}

export const store = new SimulationStore();
